// @generated by tools/generate_intl_aliases.py; do not edit.
// Source: Unicode CLDR 48.2 at 11299982335beb974c1c63c45265184e759c0f41 common/bcp47 (Unicode-3.0).

#[rustfmt::skip]
pub(super) const UNICODE_TYPE_ALIASES: &[(&str, &[(&str, &str)])] = &[
    ("ca", &[
        ("ethiopic-amete-alem", "ethioaa"),
        ("islamicc", "islamic-civil"),
    ]),
    ("kb", &[
        ("yes", "true"),
    ]),
    ("kc", &[
        ("yes", "true"),
    ]),
    ("kh", &[
        ("yes", "true"),
    ]),
    ("kk", &[
        ("yes", "true"),
    ]),
    ("kn", &[
        ("yes", "true"),
    ]),
    ("ks", &[
        ("primary", "level1"),
        ("tertiary", "level3"),
    ]),
    ("ms", &[
        ("imperial", "uksystem"),
    ]),
    ("tz", &[
        ("aqams", "aqmcm"),
        ("aukns", "auhba"),
        ("caffs", "cawnp"),
        ("camtr", "cator"),
        ("canpg", "cator"),
        ("capnt", "caiql"),
        ("cathu", "cator"),
        ("cayzf", "caedm"),
        ("cet", "bebru"),
        ("cnckg", "cnsha"),
        ("cnhrb", "cnsha"),
        ("cnkhg", "cnurc"),
        ("cst6cdt", "uschi"),
        ("cuba", "cuhav"),
        ("eet", "grath"),
        ("egypt", "egcai"),
        ("eire", "iedub"),
        ("est", "papty"),
        ("est5edt", "usnyc"),
        ("factory", "unk"),
        ("gaza", "gazastrp"),
        ("gmt0", "gmt"),
        ("hongkong", "hkhkg"),
        ("hst", "ushnl"),
        ("iceland", "isrey"),
        ("iran", "irthr"),
        ("israel", "jeruslm"),
        ("jamaica", "jmkin"),
        ("japan", "jptyo"),
        ("libya", "lytip"),
        ("met", "bebru"),
        ("mncoq", "mnuln"),
        ("mst", "usphx"),
        ("mst7mdt", "usden"),
        ("mxstis", "mxtij"),
        ("navajo", "usden"),
        ("poland", "plwaw"),
        ("portugal", "ptlis"),
        ("prc", "cnsha"),
        ("pst8pdt", "uslax"),
        ("roc", "twtpe"),
        ("rok", "krsel"),
        ("turkey", "trist"),
        ("uaozh", "uaiev"),
        ("uauzh", "uaiev"),
        ("uct", "utc"),
        ("umjon", "ushnl"),
        ("usnavajo", "usden"),
        ("wet", "ptlis"),
        ("zulu", "utc"),
    ]),
];

#[rustfmt::skip]
pub(super) const TRANSFORM_VALUE_ALIASES: &[(&str, &[(&str, &str)])] = &[
    ("d0", &[
        ("name", "charname"),
    ]),
    ("m0", &[
        ("beta-metsehaf", "betamets"),
        ("ies-jes", "iesjes"),
        ("names", "prprname"),
        ("tekie-alibekit", "tekieali"),
    ]),
];
