#!/usr/bin/env python3
"""Generate compact ECMA-402 extension alias tables from pinned CLDR data."""

from __future__ import annotations

import argparse
import re
import urllib.request
import xml.etree.ElementTree as ET
from collections import defaultdict
from pathlib import Path


CLDR_VERSION = "48.2"
CLDR_REF = "11299982335beb974c1c63c45265184e759c0f41"
CLDR_FILES = (
    "calendar",
    "collation",
    "currency",
    "measure",
    "number",
    "segmentation",
    "timezone",
    "transform-destination",
    "transform",
    "transform_hybrid",
    "transform_ime",
    "transform_keyboard",
    "transform_mt",
    "transform_private_use",
    "variant",
)
RAW_ROOT = f"https://raw.githubusercontent.com/unicode-org/cldr/{CLDR_REF}/common/bcp47"
VALUE = re.compile(r"[a-z0-9]{3,8}(?:-[a-z0-9]{3,8})*\Z")


def load_xml(name: str) -> ET.Element:
    with urllib.request.urlopen(f"{RAW_ROOT}/{name}.xml", timeout=30) as response:
        return ET.fromstring(response.read())


def collect_aliases() -> tuple[dict[str, dict[str, str]], dict[str, dict[str, str]]]:
    unicode_aliases: dict[str, dict[str, str]] = defaultdict(dict)
    transform_aliases: dict[str, dict[str, str]] = defaultdict(dict)
    for filename in CLDR_FILES:
        root = load_xml(filename)
        for key in root.iter("key"):
            key_name = key.attrib["name"].lower()
            destination = (
                transform_aliases if key.attrib.get("extension") == "t" else unicode_aliases
            )
            for type_node in key.findall("type"):
                name = type_node.attrib["name"].lower()
                canonical = type_node.attrib.get("preferred", name).lower()
                if not VALUE.fullmatch(canonical):
                    continue
                aliases = type_node.attrib.get("alias", "").split()
                if "preferred" in type_node.attrib:
                    aliases.append(name)
                for alias in aliases:
                    alias = alias.lower()
                    if alias != canonical and VALUE.fullmatch(alias):
                        previous = destination[key_name].setdefault(alias, canonical)
                        if previous != canonical:
                            raise ValueError(
                                f"conflicting {key_name}/{alias}: {previous} vs {canonical}"
                            )
    return dict(unicode_aliases), dict(transform_aliases)


def render_table(name: str, tables: dict[str, dict[str, str]]) -> list[str]:
    lines = [
        "#[rustfmt::skip]\n",
        f"pub(super) const {name}: &[(&str, &[(&str, &str)])] = &[\n",
    ]
    for key in sorted(tables):
        lines.append(f'    ("{key}", &[\n')
        for alias, canonical in sorted(tables[key].items()):
            lines.append(f'        ("{alias}", "{canonical}"),\n')
        lines.append("    ]),\n")
    lines.append("];\n")
    return lines


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("src/builtins/intl_aliases.rs"),
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    unicode_aliases, transform_aliases = collect_aliases()
    output = [
        "// @generated by tools/generate_intl_aliases.py; do not edit.\n",
        f"// Source: Unicode CLDR {CLDR_VERSION} at {CLDR_REF} common/bcp47 ",
        "(Unicode-3.0).\n\n",
    ]
    output.extend(render_table("UNICODE_TYPE_ALIASES", unicode_aliases))
    output.append("\n")
    output.extend(render_table("TRANSFORM_VALUE_ALIASES", transform_aliases))
    formatted = "".join(output)
    if args.check:
        if not args.output.is_file() or args.output.read_text(encoding="utf-8") != formatted:
            raise SystemExit(f"{args.output} is not generated from pinned CLDR data")
    else:
        args.output.write_text(formatted, encoding="utf-8")


if __name__ == "__main__":
    main()
